### ISSUE TITLE
[MVP] Hackathon platform

### ISSUE THREAD

**Issue by jptissot** [StatCan/StatCan.OrchardCore#51]
- [x] Contact Form https://github.com/StatCan/StatCan.OrchardCore/commit/273bd216a74a7a159c346d1a485eeb4b3daf9661
- [x] Login views with External provider support (#112)
- [x] Protected page (protected by roles) https://github.com/StatCan/StatCan.OrchardCore/commit/7ffd33ac0dd172b9064291fb4d141b8f16a7201e
- [x] Tab Widget https://github.com/StatCan/StatCan.OrchardCore/commit/d431e6e744aeaa19371872cee2e9c55a2190c460
- [x] Content pages https://github.com/StatCan/StatCan.OrchardCore/commit/aa732057f330681ed244ac6e02c027c82afa1edb
- [x] Schedule Widget 
- [x] Creation of Hacker, volunteer content types https://github.com/StatCan/StatCan.OrchardCore/pull/59
- [x] Hackathon CustomSettings https://github.com/StatCan/StatCan.OrchardCore/pull/59
- [x] Hacker Registration form  https://github.com/StatCan/StatCan.OrchardCore/pull/59
- [x] Volunteer Registration form  https://github.com/StatCan/StatCan.OrchardCore/pull/59
- [x] Team management (create, join, leave) https://github.com/StatCan/StatCan.OrchardCore/pull/59
- [x] Challenge list widget https://github.com/StatCan/StatCan.OrchardCore/issues/117 https://github.com/StatCan/StatCan.OrchardCore/pull/59
- [x] Challenge submission form (for authenticated users) https://github.com/StatCan/StatCan.OrchardCore/issues/117 https://github.com/StatCan/StatCan.OrchardCore/pull/59
- [x] Team list for authenticated users (can join team if not already on a team)
- [x] Team captain (can kick other members, can pick Challenge for team, can edit team description) https://github.com/StatCan/StatCan.OrchardCore/issues/128
- [x] Team description (captain can edit) https://github.com/StatCan/StatCan.OrchardCore/issues/128
- [x] Challenge (formerly case) selection for team captain  https://github.com/StatCan/StatCan.OrchardCore/issues/128

## Admin features
- [x] Admin: Get mailing list of participants
- [x] Admin: Display useful information in SummaryAdmin views (Email, Team, etc)

## Documentation
- [ ] https://github.com/StatCan/StatCan.OrchardCore/issues/56

**Comment by jonlamdev** [comment]
Make sure https://github.com/StatCan/StatCan.OrchardCore/issues/56 gets updated
